### ISSUE TITLE
possible to support "file"  install method

### ISSUE THREAD

**Issue by chrisduong** [bdangit/chef-influxdb#112]
Hi,

Since the InfluxDB repository only store the latest version at the moment. Is it possible if we can  support **install_file** method, so we can install multiple versions of InfluxDB.

I think it is important, since we can choose specific version if you don't want to upgrade at the moment.

I created the branch [file-install_method](https://github.com/chrisduong/chef-influxdb/blob/support-install-by-file/recipes/_install_file.rb) for your reference.

My kitchen snippet is:

```
  - name: file
    run_list:
      - recipe[influxdb-test::default]
    attributes:
      influxdb:
        install_type: file
        version: 0.10.3-1
```
